// Code generated by goctl. DO NOT EDIT.
package types

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type Message struct {
	Message string `json:"message"`
}

type Url struct {
	Url string `json:"url"`
}

type PredictRequest struct {
	Code string `form:"code"`
}

type PredictResponse struct {
	Message string `json:"message"`
}

type UploadRequest struct {
	Code string `form:"code"`
}

type UploadResponse struct {
	Base
	Data Message `json:"data"`
}

type SmUploadResponse struct {
	Base
	Data Url `json:"data"`
}

type DownloadFileRequest struct {
	Filename string `path:"filename"`
}

type DownloadFileResponse struct {
	Data []byte `json:"data"`
}

type SendPidRequest struct {
	CurrentPid int64 `json:"current_pid"`
}

type SendPidResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type GetPidResponse struct {
	Code       int64  `json:"code"`
	Msg        string `json:"msg"`
	CurrentPid int64  `json:"current_pid"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	Token        string `json:"token"`
}

type RegisterRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	IsAdmin    int64  `json:"isAdmin,omitempty,default=0"`
	Name       string `json:"name"`
	Number     string `json:"number"`
	UploadTime string `json:"uploadTime, optional"`
}

type RegisterResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ChangePasswordRequest struct {
	Username    string `json:"username"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ChangePhoneNumberRequest struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phonenumber"`
}

type ChangePhoneNumberResponse struct {
	Message string `json:"message"`
}

type ChangeEmailRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type ChangeEmailResponse struct {
	Message string `json:"message"`
}

type InsertDoctorInfoRequest struct {
	Email           string `json:"email"`
	Nickname        string `json:"nickname"`
	Regions         string `json:"regions"`
	SelfInformation string `json:"self_information"`
	Did             string `json:"did"`
}

type InsertDoctorInfoResponse struct {
	Message string `json:"message"`
}

type GetDoctorInfoRequest struct {
	Username string `form:"username"`
}

type GetDoctorInfoResponse struct {
	Username        string `json:"username"`
	Phonenumber     string `json:"phonenumber"`
	Id              int64  `json:"id"`
	SecretKey       string `json:"secretKey, optional"`
	Email           string `json:"email"`
	Name            string `json:"name"`
	Regions         string `json:"regions"`
	SelfInformation string `json:"self_information"`
}

type InsertCaseRequest struct {
	Body string `json:"body"`
	Cid  string `json:"cid"`
}

type InsertCaseResponse struct {
	Message string `json:"message"`
}

type QueryCaseRequest struct {
	Cid string `form:"cid"`
}

type QueryCaseResponse struct {
	Body string `json:"body"`
}

type GetDataRequest struct {
	Username string `form:"username"`
}

type GetDataResponse struct {
	CardValue string `json:"cardValue"`
	Name      string `json:"name"`
	Value     int64  `json:"value"`
}

type RemoveFilePathRequest struct {
	FilePath string `json:"file_path"`
}

type RemoveFilePathResponse struct {
	Message string `json:"message"`
}

type QuotaApplyInqueryResponse struct {
	Id          int64  `json:"id"`
	Amount      string `json:"amount"`
	Username    string `json:"username"`
	CreatedAt   string `json:"created_at"`
	QuotaAmount string `json:"quota_amount"`
}

type QuotaApplyRemoveRequest struct {
	Id int64 `json:"id"`
}

type QuotaApplyRemoveResponse struct {
	Message string `json:"message"`
}

type QuotaInquiryRequest struct {
	Username string `form:"username"`
}

type QuotaInquiryResponse struct {
	DailyCallLimit string `json:"DailyCallLimit"`
	CallNumbers    string `json:"callNumbers"`
	CallVolumes    string `json:"callVolumes"`
	Type           string `json:"type"`
}

type GetAllRequest struct {
	Did string `form:"did"`
}

type GetAllResponse struct {
	Id         int64  `json:"id"`
	Did        string `json:"did"`
	Name       string `json:"name"`
	Sex        string `json:"sex"`
	Age        int64  `json:"age"`
	UploadTime string `json:"uploadTime"`
	Code       string `json:"code"`
	FilePath   string `json:"filePath"`
}

type GetPatientFilePathRequest struct {
	Code string `form:"code"`
}

type GetPatientFilePathResponse struct {
	Key      int64  `json:"key"`
	FileName string `json:"fileName"`
}

type InsertPatientRequest struct {
	Username   string `json:"username"`
	Name       string `json:"name"`
	Sex        string `json:"sex"`
	Age        int64  `json:"age"`
	Code       int64  `json:"code, optional"`
	UploadTime string `json:"uploadTime, optional"`
}

type InsertPatientResponse struct {
	Message string `json:"message"`
}

type GetAllDataResponse struct {
	CardValue string `json:"cardValue"`
	Name      string `json:"name"`
	Value     int64  `json:"value"`
}

type RemoveDoctorRequest struct {
	Username string `json:"username"`
}

type RemoveDoctorResponse struct {
	Message string `json:"message"`
}

type RemovePatientRequest struct {
	Id int64 `json:"id"`
}

type RemovePatientResponse struct {
	Message string `json:"message"`
}

type Series struct {
	Data []int64 `json:"data"`
	Name string  `json:"name"`
	Type string  `json:"type"`
}

type XAxis struct {
	Data []string `json:"data"`
}

type ChartDataResponse struct {
	Max    int64    `json:"max"`
	Series []Series `json:"series"`
	XAxis  XAxis    `json:"xAxis"`
}

type QuotaApplyInsertRequest struct {
	Username string `json:"username"`
	Amount   int64  `json:"amount"`
}

type QuotaApplyInsertResponse struct {
	Message string `json:"message"`
}

type AddQuotaRequest struct {
	Username string `json:"username"`
	Amount   int64  `json:"amount"`
}

type AddQuotaResponse struct {
	Message string `json:"message"`
}

type AdminGetAllDoctorResponse struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Name         string `json:"name"`
	Telephone    string `json:"telephone"`
	RegisterTime string `json:"registerTime"`
}

type TestResponse struct {
	Message string `json:"message"`
}
