// Code generated by goctl. DO NOT EDIT.

package patient

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	patientInfoFieldNames          = builder.RawFieldNames(&PatientInfo{}, true)
	patientInfoRows                = strings.Join(patientInfoFieldNames, ",")
	patientInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(patientInfoFieldNames, "id"), ",")
	patientInfoRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(patientInfoFieldNames, "id"))

	cachePublicPatientInfoIdPrefix = "cache:public:patientInfo:id:"
)

type (
	patientInfoModel interface {
		Insert(ctx context.Context, data *PatientInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PatientInfo, error)
		Update(ctx context.Context, data *PatientInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPatientInfoModel struct {
		sqlc.CachedConn
		table string
	}

	PatientInfo struct {
		Id         int64          `db:"id"`
		Pid        string         `db:"pid"`
		FileName   sql.NullString `db:"file_name"`
		FilePath   sql.NullString `db:"file_path"`
		UploadDate time.Time      `db:"upload_date"`
	}
)

func newPatientInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPatientInfoModel {
	return &defaultPatientInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."patient_info"`,
	}
}

func (m *defaultPatientInfoModel) withSession(session sqlx.Session) *defaultPatientInfoModel {
	return &defaultPatientInfoModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      `"public"."patient_info"`,
	}
}

func (m *defaultPatientInfoModel) Delete(ctx context.Context, id int64) error {
	publicPatientInfoIdKey := fmt.Sprintf("%s%v", cachePublicPatientInfoIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicPatientInfoIdKey)
	return err
}

func (m *defaultPatientInfoModel) FindOne(ctx context.Context, id int64) (*PatientInfo, error) {
	publicPatientInfoIdKey := fmt.Sprintf("%s%v", cachePublicPatientInfoIdPrefix, id)
	var resp PatientInfo
	err := m.QueryRowCtx(ctx, &resp, publicPatientInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", patientInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPatientInfoModel) Insert(ctx context.Context, data *PatientInfo) (sql.Result, error) {
	publicPatientInfoIdKey := fmt.Sprintf("%s%v", cachePublicPatientInfoIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, patientInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Pid, data.FileName, data.FilePath, data.UploadDate)
	}, publicPatientInfoIdKey)
	return ret, err
}

func (m *defaultPatientInfoModel) Update(ctx context.Context, data *PatientInfo) error {
	publicPatientInfoIdKey := fmt.Sprintf("%s%v", cachePublicPatientInfoIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, patientInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.Pid, data.FileName, data.FilePath, data.UploadDate)
	}, publicPatientInfoIdKey)
	return err
}

func (m *defaultPatientInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicPatientInfoIdPrefix, primary)
}

func (m *defaultPatientInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", patientInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPatientInfoModel) tableName() string {
	return m.table
}
